#!/bin/bash
echo "get system memory info"

memtotal=`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`;
memfree=`cat /proc/meminfo | grep MemFree | awk '{print $2}'`;
let "memuse=memtotal-memfree";
echo $memtotal $memfree $memuse
